# Generated by Django 4.0.5 on 2022-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
